### PR TITLE
Introduce Travis CI

### PR DESCRIPTION
**Pull request by ohbarye**
Hello @dankimio 

I'm thinking it might be nice to introduce Travis CI so that we can detect any unexpected spec failure before merging. (e.g. https://github.com/nomad/venice/pull/44)

What do you think?

### CODE REVIEW

**Comment by dankimio** [comment]
@ohbarye Sounds great! Do we really need to update Bundler (in Ruby 2.4.1) before running specs? I think we can skip `script` specification, since `rake` runs RSpec by default.

**Comment by ohbarye** [comment]
@dankimio 
I'm so sorry for my late reply! 🙇 

> Do we really need to update Bundler (in Ruby 2.4.2) before running specs? 

Seems it's not necessary. And as you say, `script` section can be removed. 52d9547

**Comment by dankimio** [comment]
@ohbarye Thank you!

**Comment by ohbarye** [comment]
Thank you too!

**Pull request merged**
